#!/system/bin/sh

if [ ! -z "$nd" ]; then
	cd /"$nd"
fi
dir_base=/data/local/UnpackerSystem
cap_name=$(cat "$dir_base"/config/"$r_name"*_name.txt)
dir_bb=/data/local/binary

if [ -z "$("$dir_bb"/busybox hexdump -C -n 20000 "$cap_name".img | "$dir_bb"/busybox grep '3a ff 26 ed')" ]; then
	dir_loop=/data/local/"$cap_name"
	loops=$("$dir_bb"/busybox mount | cut -d" " -f1,3 | "$dir_bb"/busybox grep "$dir_loop$" | cut -d" " -f1)

	if [ ! -z "$("$dir_bb"/busybox mount | cut -d" " -f3 | "$dir_bb"/busybox grep "$dir_loop$")" ]; then
		"$dir_bb"/busybox umount "$dir_loop"
		losetup -d "$loops"
	fi

	mkdir "$dir_loop"
	"$dir_bb"/busybox mount -t ext4 -o rw,loop "$cap_name".img "$dir_loop"

	if [ "$?" -eq "0" ]; then
		echo
		echo "....."$cap_name".img смонтирован в папку: $dir_loop для получения capabilities."
		echo

		>/data/local/UnpackerSystem/config/"$cap_name"_cap.txt

		getcap -r "$dir_loop" >>/data/local/UnpackerSystem/config/"$cap_name"_cap.txt

		"$dir_bb"/busybox umount "$dir_loop"
		if [ "$?" -eq 0 ]; then
			losetup -d "$loops"
			rm -rf "$dir_loop"
			echo
			echo ".....Успешно размонтировано: "$dir_loop""
			echo
		else
			echo ".....Ошибка размонтирования!"
			echo
		fi
	else

		for i in 0 1 2 3 4 5 6 7; do
			loop=/dev/block/loop$i
			"$dir_bb"/busybox mknod $loop b 7 $i
			"$dir_bb"/busybox losetup $loop "$cap_name".img
			test "$("$dir_bb"/busybox losetup $loop | "$dir_bb"/busybox grep "$cap_name".img)" && break
		done
		"$dir_bb"/busybox mount -t ext4 -o loop $loop "$dir_loop"
		if [ "$?" -eq "0" ]; then
			echo
			echo "....."$cap_name".img смонтирован в папку: $dir_loop для получения capabilities."
			echo

			>/data/local/UnpackerSystem/config/"$cap_name"_cap.txt

			getcap -r "$dir_loop" >>/data/local/UnpackerSystem/config/"$cap_name"_cap.txt

			"$dir_bb"/busybox umount "$dir_loop"
			if [ "$?" -eq 0 ]; then
				losetup -d "$loop"
				rm -rf "$dir_loop"
				echo
				echo ".....Успешно размонтировано: "$dir_loop""
				echo
			else
				echo ".....Ошибка размонтирования!"
				echo
			fi
		else
			echo
			echo "\033[31;47;1m ...Ошибка монтирования для получения caps!    \033[0m"
			echo "\033[31;47;1m ...Capabilities не получены!                  \033[0m"
			echo
		fi
	fi
fi
