#!/system/bin/sh

myk() {
	read b
	if [ "$b" -le "7" ]; then
		echo ".....Конвертация в "$file".br...Ждём..."
		brotli -"$b"f ./"$file"
		echo
	else
		echo
		echo ".....Вводите цифру от 0 до 7:"
		myk
		echo
	fi
	if [ $(echo $?) -eq 0 ]; then
		#echo
		echo ".....Конвертация завершена!"
		echo
	else
		#echo
		echo ".....error: Ошибка при конвертации."
		echo
	fi
}

if [ -f ./"$file" ]; then
	echo
	echo ".....Введите степень сжатия(цифру от 0 до 7):"
	myk
else
	echo
	echo ".....В папке нет "$file"."
	echo
fi
