#!/system/bin/sh

dir_bb="/data/local/binary/"
dir_loop="/data/local/$a"

if [ -z "$("$dir_bb"/busybox mount | busybox cut -d" " -f3 | busybox grep "$dir_loop$")" ] ; then

 mkdir "$dir_loop"
 "$dir_bb"/busybox mount -t ext4 -o rw,loop "$file" "$dir_loop"
if [ "$?" -eq "0" ]; then
echo
echo "     $file смонтирован в папку: $dir_loop"
echo
else
      loop="$("$dir_bb"/busybox losetup -f)"
      i="$(echo "$loop" | busybox awk -F"loop" '{ print $2 }')"
      [ -e /dev/block/loop1 ] && minor=$(busybox ls -l /dev/block/loop1 | busybox awk '{ print $6 }');
      "$dir_bb"/busybox mknod $loop b 7 $(($i * $minor))
      "$dir_bb"/busybox losetup $loop "$a".img

   "$dir_bb"/busybox mount -t ext4 -o loop,noatime $loop "$dir_loop"
if [ "$?" -eq "0" ]; then
echo
echo "     $file смонтирован в папку: $dir_loop"
echo
else
echo
echo ".....Ошибка монтирования"
echo
 "$dir_bb"/busybox losetup -d $loop
fi
fi
else
echo
echo ".....Уже ранее была смонтирована папка $dir_loop"
echo
fi