#!/system/bin/sh

 #clear
 file="$1"
 file_key="$2"

if busybox test -s "$file"; then
 unset check_alg
 check_alg="$(avbtool info_image --image "$file" 2> /dev/null | busybox awk '/^Algorithm:/ { print $2 }')"
 

if busybox test "$check_alg" != "NONE" -a ! -z "$check_alg"; then

 r="$(busybox basename $file)"

 f_name=${r%.*}

 offset_avb="$(bin_utils foffset "$file" "41564230" -1 true)"

if busybox test ! -z "$offset_avb"; then

 size_magic="$(avbtool info_image --image "$file" | busybox awk '/Header Block:/ { print $3 }')"

 size_ayten="$(avbtool info_image --image "$file" | busybox awk '/Authentication Block:/ { print $3 }')"

 xxx="$(busybox expr "$offset_avb" \+ 64)"
 
 offset_key="$(busybox printf "%d\n" "0x""$(xxd -ps -s "$xxx" -l 8 "$file")")"

 xxx="$(busybox expr "$offset_avb" \+ 72)"

 size_key="$(busybox printf "%d\n" "0x""$(xxd -ps -s "$xxx" -l 8 "$file")")"
 
 size_new_key="$(busybox stat -c %s "$file_key")"
 
 real_offset_key_dec="$(busybox expr "$offset_avb" \+ "$size_magic" \+ "$size_ayten" \+ "$offset_key")"
 
 real_offset_key="$(printf "%x\n" "$real_offset_key_dec")"

 real_size_key="$(busybox expr "$real_offset_key_dec" \+ "$size_key")"

if busybox test "$size_key" == "$size_new_key"; then

 sha11="$(avbtool info_image --image "$file" | busybox awk '/^Public key \(sha1\):/ { print $4}')"

  bin_utils writekey "$file" "$real_offset_key" -f "$file_key" &>/dev/null
  
if [ $(echo $?) -eq 0 ]; then
 check_new_alg="$(avbtool info_image --image "$file" 2> /dev/null | busybox awk '/^Algorithm:/ { print $2 }')"
 
 sha12="$(avbtool info_image --image "$file" | busybox awk '/^Public key \(sha1\):/ { print $4}')"
 
if [ ! -z "$sha11" -a ! -z "$sha12" ]; then
 echo
 echo ".....Algorithm: $check_new_alg"
 echo ".....sha1 public key: $sha12"
 echo
 else
 echo ".....Ошибка при изменении ключа!"
 echo
fi
 else
 echo ".....Ошибка при изменении ключа!"
 echo
fi
 else
 echo
 echo ".....Ошибка! Размеры ключей не совпадают!"
 echo
fi
 else
 echo
 echo ".....Ошибка, не найден offset AVB0"
 echo
fi
 else
 echo
 echo ".....Файл $nd/$file не подписан!"
 echo
fi
 else
 echo
 echo ".....Нет файла для обработки!"
 echo
fi
 unset xxx
